"Tutorial Island - Avery! Hat Recipe"
"Tutorial Island - Avery! Quest Completion"
"Tutorial Island - Stick Pickup"
"Tutorial Island - Jill Quest Completion"
"Tutorial Island - Pot? Pickup"
"Tutorial Island - Martin Quest Completion"
"Tutorial Island - Simon (Ragdoll Bear) Quest Completion"
"Tutorial Island - ??? (Bracelet Monkey) Tutorial Bracelet"
"Tutorial Island - Franny (Stick Duck) Quest Completion"
"Tutorial Island - Gerald (Slime Giraffe) Quest Completion"
"Tutorial Island - Race Next to Martin"
"Tutorial Island - Race Farther from Martin"
"Tutorial Island - Pot on Rock near Stick Pickup"
"Tutorial Island - Pot on down path behind Stick Pickup"
"Tutorial Island - Pot between two waterfalls below ???"
"Tutorial Island - Pot between two waterfalls on level with ???"
"Tutorial Island - Pot on grassy cliff behind races"
"Tutorial Island - Pot on grassy cliff above north east"
"Tutorial Island - Pot overlooking rope bridge (to the north)"
"Tutorial Island - Pot behind tall cliffs to north"
"Tutorial Island - Chest behind Gerald"
"Tutorial Island - Pot on cliffs in front of Gerald (1)"
"Tutorial Island - Pot on cliffs in front of Gerald (2)"
"Tutorial Island - Pot on cliffs in front of Gerald (3)"
"Tutorial Island - Pot by three ropes (highest)"
"Tutorial Island - Pot by three ropes (middle)"
"Tutorial Island - Pot by three ropes (lowest)"
"Tutorial Island - Pot on small triangular outcropping"
"Tutorial Island - Pot on pillar"
"Tutorial Island - Pot on north tall cliffs"
"Tutorial Island - Pot on south tall cliffs, north end"
"Tutorial Island - Pot on south tall cliffs, middle"
"Tutorial Island - Pot on south tall cliffs, south end"
"Tutorial Island - Chest on south tall cliffs, south end"
"Tutorial Island - Pot southeast of Jill at sea level (1)"
"Tutorial Island - Pot southeast of Jill at sea level (2)"
"Tutorial Island - Chest southeast of Jill"
"Tutorial Island - Pot overlooking Jill"
"Tutorial Island - Chest visible from bone path"
"Central (Ravine) - Esther (Directions Deer) Quest Completion"
"Central (Ravine) - Pot south of Esther"
"Main Island - ??? (Bracelet Monkey) Windmill Bracelet"
"Main Island - ??? (Bracelet Monkey) Mountain Bracelet"
"Main Island - ??? (Bracelet Monkey) Tree Bracelet"
"Main Island - Billy (Whale) Quest Completion"
"Main Island - Darcie (Balloon Owl) Quest Completion"
"Main Island - Skate Pug (Skate Pug) Quest Completion"
"Main Island - Twig (Flip Pomeranian) Quest Completion"
"Main Island - Viraj (Hot Shot Elephant) Quest Completion"
"Main Island - Eva (Photographer Cat) Quest Completion"
"Main Island - Sam (Pencil Jackal) Quest Completion"
"Main Island - Sierra (Origami Rhea) Quest Completion"
"Main Island - Romeo (Ninja Rat) Quest Completion"
"Main Island - Oscar (Outcast Tiger) Quest Completion"
"Main Island - Joe (Pose Hawk) Quest Completion"
"Main Island - Broken Scooter Board Pickup (Kasen's Quest)"
"Main Island - Kasen (Scooter Vulture) Quest Completion"
"Main Island - Bowling Bomb Gift (Flint's Quest)"
"Main Island - Flint (BombBowl Mole) Quest Completion"
"Main Island - Ssumantha (Waders Opposum) Quest Completion"
"Main Island - Pot Kid (Eepy Armadillo) Quest Completion"
"Main Island - Scooter (Ceramic-Allegy Leopard) Quest Completion"
"Main Island - Leeland (Painting Rabbit) Quest Completion"
"Main Island - Trish (Invisible Horse) Quest Completion"
"Main Island - Retainer Pickup (Becca's Quest)"
"Main Island - Becca (Retainer Shark) Quest Completion"
"Main Island - Luisa (Tripping Lizard) Quest Completion"
"Main Island - Madeline (Little Thing Mouse) Quest Completion"
"Main Island - Pepperoni (Obstacle Ostrich) Quest Completion"
"Main Island - Mochi (Heights Bear) Quest Completion"
"Main Island - Sorin, Roe, Beeritney (Lunch Trio) Quest Completion"
"Main Island - Rock (Zhu's Quest)"
"Main Island - Zhu (Skipping Fox) Quest Completion"
"Main Island - Gunther (Sidekick Hippo) Quest Completion"
"Main Island - Tony (Chess Strategist Eagle) Quest Completion"
"Main Island - Neil (Peptalk Rat) Quest Completion"
"Main Island - Robin (Scared-to-Look Robin) Quest Completion"
"Main Island - Penelope (Bastion Beaver) Quest Completion"
"Main Island - Mr. Doddler (No Littering Bird) Quest Completion"
"Main Island - Cade (Floofy Bull) Quest Completion"
"Main Island - Tiffany (Princess Cat) Quest Completion"
"Main Island - Tanner (Pot Mimic Elk) Quest Completion"
"Avery!'s Main Quest - Nerf Blaster (Andromeda's Quest)"
"Avery!'s Main Quest - Andromeda (Space Hawk) Quest Completion"
"Avery!'s Main Quest - Velma (Western Cow) Quest Completion"
"Avery!'s Main Quest - Sorbet (Esme's Quest)"
"Avery!'s Main Quest - Plastic Fangs (Esme's Quest)"
"Avery!'s Main Quest - Esme (Vampire Bat) Quest Completion"
"Avery!'s Main Quest - Avery!'s Main Quest Quest Completion"
"Jill's Main Quest - Magic Ore Pickup (Susanne's Quest)"
"Jill's Main Quest - Susanne (Paleolithic Antelope) Quest Completion"
"Jill's Main Quest - Cheese Sandwich Pickup (Gene's Quest)"
"Jill's Main Quest - Gene (Merchant Beaver) Quest Completion"
"Jill's Main Quest - Bug Net Gift (Antone's Quest)"
"Jill's Main Quest - Antone (Beetle-Loving Iguana) Quest Completion"
"Jill's Main Quest - Jill's Main Quest Completion"
"Martin's Main Quest - Martin Shield (Lucas's Quest)"
"Martin's Main Quest - Lucas (Cool Wolf) Quest Completion"
"Martin's Main Quest - Bucket Gift (Jada's Quest)"
"Martin's Main Quest - Big Leaf Gift (Jada's Quest)"
"Martin's Main Quest - Jada (Cool Boar) Quest Completion"
"Martin's Main Quest - Duke (Cool Goose) Quest Completion"
"Martin's Main Quest - Martin's Main Quest Completion"
"Junk 4 Trash - Sticky Hand Purchase"
"Junk 4 Trash - Trampoline Purchase"
"Junk 4 Trash - Trash Can Lid Purchase"
"Junk 4 Trash - Wrench Purchase"
"Junk 4 Trash - Space Dome Purchase"
"Junk 4 Trash - Grabby Hand Purchase"
"Junk 4 Trash - Roy (Trash Raccoon) All Purchases"